### ISSUE TITLE
[AspireE2E]Aspire init does not generate Projects.* bindings causing AddProject<T> compile failure (CS0234)

### ISSUE THREAD

**Issue by Chakolito** [microsoft/aspire#16851]
**REGRESSION INFO:** Works well in aspire cli 13.2.4

**INSTALL STEPS**
1. Clean machine: Win11 x64 25h2 ENU.
2. Install SDK 10.0.300.
3. Add feed.
4. Install Aspire 13.3 CLI.

**REPRO STEPS**
1. Open CMD and create a Blazor WebAssembly Global App.
```
dotnet new blazor -int WebAssembly -ai -o WebAssembly
```
2. Navigate to the solution folder, and run aspire init.
```
cd WebAssembly
aspire init
```
3. Open WebAssembly.AppHost/AppHost.cs file and the code below.
```
builder.AddProject<Projects.WebAssembly>("webassembly");
```
4. Go to WebAssembly.AppHost project.
```
cd WebAssembly.AppHost
```
5. Run the Aspire project.
```
aspire run
```

**ACTUAL**

<img width="1149" height="341" alt="Image" src="https://github.com/user-attachments/assets/bc1d1852-edba-45e1-a665-7f3e0ff785d5" />

error CS0234: The type or namespace name 'WebAssembly'
does not exist in the namespace 'Projects' (are you missing an assembly reference?)

**Expected**
The project will run successfully without errors.

**Note**
1. A PR referencing this aspire init change https://github.com/microsoft/aspire/pull/16822
 
<details><summary>Log Info</summary>
 
```text
[2026-05-07 10:19:29.454] [INFO] [Program] Version: 13.3.0+4517e4a1ffb7f00a4c0e66882c2db952d637c0cc
[2026-05-07 10:19:29.454] [INFO] [Program] Build ID: 13.300.26.25605
[2026-05-07 10:19:29.454] [INFO] [Program] Working directory: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:29.454] [INFO] [Program] Log file: C:\Users\v-ctamayo\.aspire\logs\cli_20260507T101929_a996f9fb.log
[2026-05-07 10:19:29.454] [INFO] [Program] CLI process ID: 18648
[2026-05-07 10:19:29.461] [DBUG] [Host] Hosting starting
[2026-05-07 10:19:29.533] [DBUG] [Host] Hosting started
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature defaultWatchEnabled = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature execCommandEnabled = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature experimentalPolyglot:go = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature experimentalPolyglot:java = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature experimentalPolyglot:python = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature experimentalPolyglot:rust = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature nugetSignatureVerificationEnabled = True (default: True)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature showAllTemplates = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature showDeprecatedPackages = False (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature stagingChannelEnabled parsed value: True
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature stagingChannelEnabled = True (default: False)
[2026-05-07 10:19:29.559] [DBUG] [Features] Feature updateNotificationsEnabled = True (default: True)
[2026-05-07 10:19:29.570] [DBUG] [Features] Feature stagingChannelEnabled parsed value: True
[2026-05-07 10:19:29.573] [DBUG] [Features] Feature stagingChannelEnabled parsed value: True
[2026-05-07 10:19:29.578] [INFO] [Program] Command: aspire run
[2026-05-07 10:19:29.578] [DBUG] [Program] Parsing arguments: run
[2026-05-07 10:19:29.578] [DBUG] [Program] Executing command: aspire run
[2026-05-07 10:19:29.578] [DBUG] [AuxiliaryBackchannelMonitor] Current command is not MCP start command. Auxiliary backchannel monitoring disabled.
[2026-05-07 10:19:29.578] [DBUG] [BundleService] Ensuring bundle is extracted to C:\Users\v-ctamayo\.aspire.
[2026-05-07 10:19:29.578] [DBUG] [BundleService] Acquiring bundle extraction lock at C:\Users\v-ctamayo\.aspire\.aspire-bundle-lock...
[2026-05-07 10:19:29.578] [DBUG] [ProjectLocator] Finding project file in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:29.579] [DBUG] [BundleService] Bundle extraction lock acquired.
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: CLI at C:\Users\v-ctamayo\.aspire\bin, checking for layout...
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire\bin
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   bundle/managed/: MISSING
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   bundle/dcp/: MISSING
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   managed/: MISSING
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   dcp/: MISSING
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery] TryInferLayout: Layout rejected - missing required directories
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: Checking parent directory C:\Users\v-ctamayo\.aspire...
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   bundle/managed/: exists
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   bundle/dcp/: exists
[2026-05-07 10:19:29.579] [DBUG] [LayoutDiscovery]   bundle/managed/aspire-managed.exe: exists
[2026-05-07 10:19:29.580] [DBUG] [LayoutDiscovery] TryInferLayout: New bundle/ layout is valid
[2026-05-07 10:19:29.580] [DBUG] [LayoutDiscovery] Discovered layout relative to CLI: C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.580] [INFO] [ProjectLocator] Found AppHost path 'WebAssembly.AppHost.csproj' from config file in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:29.580] [DBUG] [AppHostProjectFactory] TryGetProject called for file: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:29.580] [DBUG] [AppHostProjectFactory] Language detected: csharp for file: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:29.580] [DBUG] [ProcessExecutionFactory] Running dotnet in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost with args: msbuild -getProperty:MSBuildVersion,IsAspireHost,AspireHostingSDKVersion -getItem:PackageReference,AspireProjectOrPackageReference C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:29.580] [DBUG] [ProcessExecutionFactory] dotnet env: ASPIRE_CLI_PID=18648
[2026-05-07 10:19:29.580] [DBUG] [ProcessExecutionFactory] dotnet env: ASPIRE_CLI_STARTED=1778149169
[2026-05-07 10:19:29.580] [DBUG] [ProcessExecutionFactory] dotnet env: MSBUILDTERMINALLOGGER=false
[2026-05-07 10:19:29.580] [DBUG] [ProcessExecutionFactory] dotnet env: DOTNET_NOLOGO=1
[2026-05-07 10:19:29.580] [DBUG] [BundleService] Version mismatch: existing=13.2.4+dd5916f8e3280da5dc491e39b19aeb5b8817a669|132756808|639126298700000000, current=13.3.0+4517e4a1ffb7f00a4c0e66882c2db952d637c0cc|135453472|639136671680000000. Re-extracting.
[2026-05-07 10:19:29.580] [INFO] [BundleService] Extracting embedded bundle to C:\Users\v-ctamayo\.aspire...
[2026-05-07 10:19:29.581] [DBUG] [BundleService] Reusing existing versioned layout at C:\Users\v-ctamayo\.aspire\versions\13.3.0_4517e4a1ffb7f00a4c0e66882c2db952d637c0cc-090fd862be3f4f7b.
[2026-05-07 10:19:29.583] [DBUG] [BundleService] Linked C:\Users\v-ctamayo\.aspire\bundle -> C:\Users\v-ctamayo\.aspire\versions\13.3.0_4517e4a1ffb7f00a4c0e66882c2db952d637c0cc-090fd862be3f4f7b
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: CLI at C:\Users\v-ctamayo\.aspire\bin, checking for layout...
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire\bin
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery]   bundle/managed/: MISSING
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery]   bundle/dcp/: MISSING
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery]   managed/: MISSING
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery]   dcp/: MISSING
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery] TryInferLayout: Layout rejected - missing required directories
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: Checking parent directory C:\Users\v-ctamayo\.aspire...
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.583] [DBUG] [LayoutDiscovery]   bundle/managed/: exists
[2026-05-07 10:19:29.584] [DBUG] [LayoutDiscovery]   bundle/dcp/: exists
[2026-05-07 10:19:29.584] [DBUG] [LayoutDiscovery]   bundle/managed/aspire-managed.exe: exists
[2026-05-07 10:19:29.584] [DBUG] [LayoutDiscovery] TryInferLayout: New bundle/ layout is valid
[2026-05-07 10:19:29.584] [DBUG] [LayoutDiscovery] Discovered layout relative to CLI: C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.584] [DBUG] [BundleService] Version marker written (version: 13.3.0+4517e4a1ffb7f00a4c0e66882c2db952d637c0cc|135453472|639136671680000000).
[2026-05-07 10:19:29.587] [DBUG] [ProcessExecutionFactory] dotnet(6728) started in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:29.587] [DBUG] [ProcessExecutionFactory] dotnet(6728) waiting for exit
[2026-05-07 10:19:29.587] [DBUG] [ProcessExecutionFactory] dotnet(6728) starting to forward stdout stream
[2026-05-07 10:19:29.588] [DBUG] [ProcessExecutionFactory] dotnet(6728) starting to forward stderr stream
[2026-05-07 10:19:29.659] [DBUG] [BundleService] Removed legacy directory at C:\Users\v-ctamayo\.aspire\managed.
[2026-05-07 10:19:29.674] [DBUG] [BundleService] Removed legacy directory at C:\Users\v-ctamayo\.aspire\dcp.
[2026-05-07 10:19:29.674] [DBUG] [BundleService] Bundle extraction verified successfully.
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: CLI at C:\Users\v-ctamayo\.aspire\bin, checking for layout...
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire\bin
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   bundle/managed/: MISSING
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   bundle/dcp/: MISSING
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   managed/: MISSING
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   dcp/: MISSING
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery] TryInferLayout: Layout rejected - missing required directories
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery] TryDiscoverRelativeLayout: Checking parent directory C:\Users\v-ctamayo\.aspire...
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery] TryInferLayout: Checking layout at C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   bundle/managed/: exists
[2026-05-07 10:19:29.674] [DBUG] [LayoutDiscovery]   bundle/dcp/: exists
[2026-05-07 10:19:29.675] [DBUG] [LayoutDiscovery]   bundle/managed/aspire-managed.exe: exists
[2026-05-07 10:19:29.675] [DBUG] [LayoutDiscovery] TryInferLayout: New bundle/ layout is valid
[2026-05-07 10:19:29.675] [DBUG] [LayoutDiscovery] Discovered layout relative to CLI: C:\Users\v-ctamayo\.aspire
[2026-05-07 10:19:29.675] [DBUG] [BundleNuGetPackageCache] Running NuGet search via aspire-managed: Aspire.Cli
[2026-05-07 10:19:29.675] [DBUG] [BundleNuGetPackageCache] aspire-managed path: C:\Users\v-ctamayo\.aspire\bundle\managed\aspire-managed.exe
[2026-05-07 10:19:29.675] [DBUG] [BundleNuGetPackageCache] NuGet search args: nuget search --query Aspire.Cli --take 1000 --format json --prerelease --working-dir C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost --verbose
[2026-05-07 10:19:29.675] [DBUG] [BundleNuGetPackageCache] Working directory: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:30.450] [DBUG] [ProcessExecutionFactory] dotnet(6728) exited with code: 0
[2026-05-07 10:19:30.450] [DBUG] [ProcessExecutionFactory] dotnet(6728) forwarders completed
[2026-05-07 10:19:30.450] [DBUG] [ProjectLocator] Using AppHost path from settings without scanning: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:30.452] [DBUG] [ProjectLocator] Config at C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\aspire.config.json already references apphost C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj, skipping creation
[2026-05-07 10:19:30.452] [DBUG] [AppHostProjectFactory] TryGetProject called for file: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:30.452] [DBUG] [AppHostProjectFactory] Language detected: csharp for file: C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] Running dotnet in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost with args: build C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] dotnet env: DOTNET_CLI_USE_MSBUILD_SERVER=true
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] dotnet env: ASPIRE_CLI_PID=18648
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] dotnet env: ASPIRE_CLI_STARTED=1778149169
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] dotnet env: MSBUILDTERMINALLOGGER=false
[2026-05-07 10:19:30.557] [DBUG] [ProcessExecutionFactory] dotnet env: DOTNET_NOLOGO=1
[2026-05-07 10:19:30.563] [DBUG] [ProcessExecutionFactory] dotnet(21976) started in C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost
[2026-05-07 10:19:30.563] [DBUG] [ProcessExecutionFactory] dotnet(21976) waiting for exit
[2026-05-07 10:19:30.563] [DBUG] [ProcessExecutionFactory] dotnet(21976) starting to forward stdout stream
[2026-05-07 10:19:30.564] [DBUG] [ProcessExecutionFactory] dotnet(21976) starting to forward stderr stream
[2026-05-07 10:19:30.642] [DBUG] [BundleNuGetPackageCache] NuGetHelper stderr: Using source from config: nuget.org (https://api.nuget.org/v3/index.json)
Using source from config: aspire13.3 (https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-microsoft-aspire-4517e4a1/nuget/v3/index.json)
Using source from config: net10 (https://pkgs.dev.azure.com/dnceng/internal/_packaging/10.0.300-servicing.26230.102-shipping/nuget/v3/index.json)
Searching 3 source(s) for 'Aspire.Cli'
Searching nuget.org (https://api.nuget.org/v3/index.json)...
Found 2 search endpoints.
Querying https://azuresearch-usnc.nuget.org/query?q=Aspire.Cli&skip=0&take=1000&prerelease=true&semVerLevel=2.0.0
Searching aspire13.3 (https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-microsoft-aspire-4517e4a1/nuget/v3/index.json)...
Found 1 search endpoints.
Querying https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aabf53ec-93e0-460e-85a2-94ebc713778c/nuget/v3/query2/?q=Aspire.Cli&skip=0&take=1000&prerelease=true&semVerLevel=2.0.0
Searching net10 (https://pkgs.dev.azure.com/dnceng/internal/_packaging/10.0.300-servicing.26230.102-shipping/nuget/v3/index.json)...
Found 1 search endpoints.
Querying https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/17e51715-27e5-452f-af23-c0411e1d78e5/nuget/v3/query2/?q=Aspire.Cli&skip=0&take=1000&prerelease=true&semVerLevel=2.0.0

[2026-05-07 10:19:30.642] [DBUG] [BundleNuGetPackageCache] NuGet search returned 103672 bytes
[2026-05-07 10:19:31.198] [INFO] [Build]   Determining projects to restore...
[2026-05-07 10:19:31.744] [INFO] [Build]   All projects are up-to-date for restore.
[2026-05-07 10:19:34.078] [INFO] [Build] C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\AppHost.cs(2,29): error CS0234: The type or namespace name 'WebAssembly' does not exist in the namespace 'Projects' (are you missing an assembly reference?) [C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj]
[2026-05-07 10:19:34.216] [INFO] [Build] 
[2026-05-07 10:19:34.216] [INFO] [Build] Build FAILED.
[2026-05-07 10:19:34.216] [INFO] [Build] 
[2026-05-07 10:19:34.216] [INFO] [Build] C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\AppHost.cs(2,29): error CS0234: The type or namespace name 'WebAssembly' does not exist in the namespace 'Projects' (are you missing an assembly reference?) [C:\Users\v-ctamayo\WebAssembly\WebAssembly.AppHost\WebAssembly.AppHost.csproj]
[2026-05-07 10:19:34.216] [INFO] [Build]     0 Warning(s)
[2026-05-07 10:19:34.216] [INFO] [Build]     1 Error(s)
[2026-05-07 10:19:34.216] [INFO] [Build] 
[2026-05-07 10:19:34.216] [INFO] [Build] Time Elapsed 00:00:03.38
[2026-05-07 10:19:34.240] [DBUG] [ProcessExecutionFactory] dotnet(21976) exited with code: 1
[2026-05-07 10:19:34.240] [DBUG] [ProcessExecutionFactory] dotnet(21976) forwarders completed
[2026-05-07 10:19:34.246] [INFO] [Stdout] ❌ The project could not be built. See logs at C:\Users\v-ctamayo\.aspire\logs\cli_20260507T101929_a996f9fb.log
[2026-05-07 10:19:34.247] [DBUG] [CliUpdateNotifier] Current version: 13.3.0
Newest stable version: 13.3.0
Newest prerelease version: (null)
[2026-05-07 10:19:34.247] [DBUG] [CliUpdateNotifier] No newer version for the current version 13.3.0.
[2026-05-07 10:19:34.247] [INFO] [Program] Exit code: 6
[2026-05-07 10:19:34.247] [DBUG] [Host] Hosting stopping
[2026-05-07 10:19:34.247] [DBUG] [Host] Hosting stopped
``

**Comment by joperezr** [comment]
I'm not sure how this worked well in 13.2.4. From your steps, you are not adding the project reference from the apphost to the webapp project, right? That step is required and is what generates the necessary code for this to compile. Can you clarify if you are adding a project reference?

**Comment by Chakolito** [comment]
I added tha project reference to the apphost.cs with the step 3: builder.AddProject<Projects.WebAssembly>("webassembly");
I think it worked well to the 13.2.4 due to the change with the aspire init command for 13.3.0.

image below is using the 13.2.4 

<img width="1737" height="887" alt="Image" src="https://github.com/user-attachments/assets/86a7ba34-4e1e-4e92-afac-9143183e516e" />

<img width="1883" height="566" alt="Image" src="https://github.com/user-attachments/assets/b08cf000-a1c5-4c56-8fdc-94e33c467047" />

**Comment by joperezr** [comment]
Thanks for the screenshots! I think there's a mix-up in terminology — calling `builder.AddProject<Projects.WebAssembly>("webassembly")` in `AppHost.cs` is not the same as adding a project reference. The `Projects.WebAssembly` type is generated by the source generator only when your AppHost project (`WebAssembly.AppHost.csproj`) has an MSBuild `<ProjectReference>` pointing at the WebAssembly app project (`WebAssembly.csproj`).

Could you try this and let us know if it resolves the CS0234?

From the `WebAssembly.AppHost` directory:

```
dotnet add reference ../WebAssembly/WebAssembly.csproj
```

Then `dotnet build` (or `aspire run`) again. If after adding the reference the `Projects.WebAssembly` type still doesn't resolve, that would indicate a real regression in 13.3 and we'll dig in further.

**Comment by jinzhao1127** [comment]
> Could you try this and let us know if it resolves the CS0234?
> 
> From the `WebAssembly.AppHost` directory:
> 
> ```
> dotnet add reference ../WebAssembly/WebAssembly.csproj
> ```

Yes, after adding the reference from `WebAssembly.AppHost` directory, will resolve this issue. 
It seems that the `aspire init` behavior has changed from 13.3. On Aspire 13.2, it does not need to add the project reference. 

   <img width="1256" height="415" alt="Image" src="https://github.com/user-attachments/assets/a3eaafa8-1ba6-4fb8-a46e-2b0bb9c0d0ab" />
   <img width="1413" height="489" alt="Image" src="https://github.com/user-attachments/assets/ca7117cf-6abc-4b0a-9532-2f98f3e32daa" />

**Comment by joperezr** [comment]
Yes, the behavior indeed changed. Init now is very simplistic and only drops an empty apphost and a skill, as the intent is to leverage agents to use that skill for better aspirification with your app. Given the behavior you are seeing is by design, I will close this for now but feel free to reopen if you think something here should change.
