### ISSUE TITLE
Aspire.Cli.Tests fails to build on main — compile errors from #16683

### ISSUE THREAD

**Issue by ellahathaway** [microsoft/aspire#17090]
### Description

`Aspire.Cli.Tests` fails to build on `main` with two compile errors introduced by #16683 (merged at `5c8aa3df`). This blocks all CLI test jobs (ubuntu, macOS, windows) on `main` and any PR that includes the CLI test project.

### Build errors

```
TestProcessExecutionFactory.cs(143,20): error CS4016: Since this is an async method,
  the return expression must be of type 'int' rather than 'Task<int>'

DashboardRunCommandTests.cs(343,72): error CS1593: Delegate
  'Func<int, ProcessInvocationOptions, CancellationToken, Task<(int ExitCode, string? Stdout)>>'
  does not take 2 arguments
```

### Root cause

1. **`TestProcessExecutionFactory.cs:143`** — `WaitForExitAsyncCallback` returns `Task<int>`, but it's returned directly from `async Task<int> WaitForExitAsync(...)` without `await`, triggering CS4016.

2. **`DashboardRunCommandTests.cs:343`** — A callback is constructed with 2 parameters but the delegate now expects 3 (`int`, `ProcessInvocationOptions`, `CancellationToken`) after the signature change in #16683.

### Failing CI

- Main CI run: https://github.com/microsoft/aspire/actions/runs/25867012211 (`Cli (ubuntu-latest)` failed)
- Also blocking PR CI, e.g. #17061

### Suggested fix

1. In `TestProcessExecutionFactory.cs:143`, change `return WaitForExitAsyncCallback(...)` to `return await WaitForExitAsyncCallback(...)`
2. In `DashboardRunCommandTests.cs:343`, update the callback to accept the 3-parameter delegate signature

**Comment by joperezr** [comment]
<details><summary>🤖 Aspire triage pass — 2026-05-14 19:33 UTC</summary>

**Area**: `area-cli`
**Kind**: regression (build break on `main`)
**Repro**: yes-minimal — issue body cites exact file/line locations and root cause (lines covering `TestProcessExecutionFactory.cs:143` and `DashboardRunCommandTests.cs:343`)
**Affected version(s)**: `main` branch HEAD after #16683 merged at `5c8aa3df` (does not affect any shipped release)
**Severity**: S2 — `Aspire.Cli.Tests` fails to build, blocking all CLI test jobs (ubuntu/macOS/windows) on `main` and on any PR that includes the CLI test project; no workaround other than reverting/fixing.

**Urgency**: 🟡 vNext — recommend milestone **13.4**
Reason: Build break is on `main` only (target branch for 13.4). The breaking change (#16683) has not shipped in 13.3.x bits, so this is not a servicing candidate. Should be fixed immediately on `main` to unblock CI.

**Suggested owner(s)**: @JamesNK (primary), backup @danegsta
Evidence:
 - @JamesNK has the strongest recent ownership of `area-cli` — merged many CLI PRs in the last 30–90 days including #17005 ("Refactor CLI commands to return CommandResult and centralize cancellation handling"), #16996, #16939, #16829, #16773, and closed/completed `area-cli` issues #16727, #16692, #16646, #16619, #16236, #16037, #15986. The signature change that produced CS1593 in `DashboardRunCommandTests.cs:343` is closely related to #17005's cancellation-handling refactor.
 - @danegsta authored the regressing PR #16683 ("Avoid copying NuGet integration assets during AppHost restore", merged 2026-05-14 14:52 UTC) and has additional recent `area-cli` closes (#16568, #16308), so is the natural backup / immediate fixer.

**Confidence**: high
**Needs human?**: no

_Dry-run mode — no labels or milestone applied. Reply `/triage apply` to promote, or edit and reapply._
</details>

**Comment by davidfowl** [comment]
Confirmed this is already fixed on current `main` by #17086 (`df3ec8d`). The failing sites now match the callback signature changes from #16683:

- `TestProcessExecutionFactory.WaitForExitAsync` awaits `WaitForExitAsyncCallback`.
- `DashboardRunCommandTests.DashboardRunCommand_WhenCancelled_DisplaysCancellationMessageAndReturnsSuccess` uses the updated callback shape.

I also verified `Aspire.Cli.Tests` locally with:

```powershell
dotnet test --project tests\Aspire.Cli.Tests\Aspire.Cli.Tests.csproj --no-launch-profile -- --filter-not-trait quarantined=true --filter-not-trait outerloop=true
```

No further fix appears needed; this issue can be closed.
