### ISSUE TITLE
Outerloop build-broken: TelemetryConfigurationTests.cs uses DefaultTimeout() under #if DEBUG, fails Release compile

### ISSUE THREAD

**Issue by radical** [microsoft/aspire#18488]
The scheduled **outerloop** lane is build-broken. Its *"Generate test runsheet"* step builds the whole solution in **Release** and fails to compile, so the lane produces **zero test signal**. Because it's a deterministic compile error, the outerloop's unconditional rerun can't clear it.

Failed run: https://github.com/microsoft/aspire/actions/runs/28144132335

Surfaced by the CI Daily Pulse: #18232.

## Error

```
error CS1061: 'Task' does not contain a definition for 'DefaultTimeout' and no accessible extension method 'DefaultTimeout' accepting a first argument of type 'Task' could be found
  tests/Aspire.Cli.Tests/Telemetry/TelemetryConfigurationTests.cs:100
  tests/Aspire.Cli.Tests/Telemetry/TelemetryConfigurationTests.cs:131
```

## Root cause

`TelemetryConfigurationTests.cs` calls `.DefaultTimeout()` on a `Task` at lines 100 and 131. The `DefaultTimeout` extension methods live in namespace `Microsoft.AspNetCore.InternalTesting` (shared `tests/Shared/AsyncTestHelpers.cs`), but the test file imports that namespace **only under `#if DEBUG`**:

```csharp
#if DEBUG
using Microsoft.AspNetCore.InternalTesting;
#endif
```

- Rolling CI's `Cli` job builds **Debug** -> the `using` is present -> compiles, tests green on all three OSes.
- The outerloop runsheet step runs `./build.sh --test -c Release` (`.github/workflows/specialized-test-runner.yml`) -> in **Release** the `using` is excluded -> `DefaultTimeout` is unresolved -> `CS1061`.

So the break is specific to the Release full-solution build the outerloop runsheet performs, not a main-wide regression. Introduced by #18251.

## Fix

Move `using Microsoft.AspNetCore.InternalTesting;` out of the `#if DEBUG` guard in `tests/Aspire.Cli.Tests/Telemetry/TelemetryConfigurationTests.cs` so the `DefaultTimeout` extension resolves in both Debug and Release.

## Investigation (please answer in the PR)

Beyond the fix, determine:

1. **What introduced the `#if DEBUG`-guarded `using`.** Confirm whether #18251 added the guard, or whether the `DefaultTimeout()` call sites were added against a pre-existing guard. Quote the relevant diff.
2. **Why PR CI did not catch it.** PR validation compiles `Aspire.Cli.Tests` (the `Cli` job) but apparently only in Debug, while the outerloop runsheet is the only lane that compiles the test tree in Release. Verify this: does any PR-triggered job build the test projects in Release? If not, that's the gap — a Release-only compile break has no PR signal until the scheduled outerloop runs.
3. **Whether the gap is systemic.** Are there other `#if DEBUG`-guarded `using` directives (or other Debug-only constructs) in test files that could similarly break the Release runsheet build? If so, list them.
4. **Prevention.** Recommend (and, if cheap, implement) a guardrail so a Release-only test-compile break is caught on PRs rather than only by the scheduled outerloop — e.g. compiling the test runsheet in Release as part of PR CI, or removing the Debug-only namespace guard pattern.

**Comment by radical** [comment]
Fixed in https://github.com/microsoft/aspire/pull/18489 .
