### ISSUE TITLE
Aspire TS + Orleans - Argument of type 'OrleansService' is not assignable to parameter of type 'OrleansServiceClientHandle'

### ISSUE THREAD

**Issue by kadamgreene** [microsoft/aspire#17666]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using Aspire 13.3.5 with Typescript:

``` typescript
// Orleans service — clustering, grain storage, and streaming wired at the AppHost level
const orleans = await builder.addOrleans("default")
    .withDevelopmentClustering()
    .withGrainStorage("Default", grainstate)
    .withGrainStorage("PubSubStore", pubsubstore)
    .withStreaming("Default", queuestorage);

// Orleans silo
const server = await builder.addProject("server", "./Server/Server.csproj", { launchProfileOrOptions: "https" })
    .withReference(orleans)
```

the `.withReference` throws an exception:
```
error TS2345: Argument of type 'OrleansService' is not assignable to parameter of type 'OrleansServiceClientHandle'.
  Type 'OrleansService' is missing the following properties from type 
'Handle<"Aspire.Hosting.Orleans/Aspire.Hosting.Orleans.OrleansServiceClient">': $handle, $type
```

### Expected Behavior

It should properly register Orleans server settings with the given .NET ASP.NET application.

### Aspire doctor output

Aspire Environment Check
========================

Container Runtime
  ✅ Docker: running (auto-detected (default)) ← active  

Environment
  ✅ TypeScript AppHost tooling found (npm, npx).  
  ✅ HTTPS development certificate is trusted  

Summary: 3 passed, 0 warnings, 0 failed

**Comment by MihuBot** [comment]
I'm a bot. Here is a possible related and/or duplicate issue (I may be wrong):
- https://github.com/dotnet/orleans/issues/9267

**Comment by sebastienros** [comment]
You need to use `withOrleansReference` in this case.

This was introduced in https://github.com/microsoft/aspire/pull/16881 because`withReference` comes from `Aspire.Hosting` and this one would conflict.

**Comment by kadamgreene** [comment]
Is this released yet?  I tried it with 13.3.5 and it says:

**error TS2339: Property 'withOrleansReference' does not exist on type 'ProjectResourcePromise'**

**Comment by sebastienros** [comment]
No, only next release. You can try with the "dev" channel (main branch release) but there may be other breaking changes depending on what you use. This will be part of 13.4.0 though, shipped soon.

**Comment by sebastienros** [comment]
For reference I also fixed the documentation https://github.com/microsoft/aspire.dev/pull/1124
